theme: jekyll-theme-minimal
title: Mayx的博客
logo: https://avatars0.githubusercontent.com/u/17966333
author: mayx
excerpt_separator: <!--more-->
paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  path: atom.xml
google_analytics: UA-137710294-1
